### ISSUE TITLE
JOSS Review (@rgmyr): ZLIB not found by CMake

### ISSUE THREAD

**Issue by rgmyr** [kellykochanski/rescal-snow#26]
Following the installation notes as written resulted in a CMake error:
```
CMake Error at /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.13/Modules/FindZLIB.cmake:114 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  lib/libpng-1.6.37/CMakeLists.txt:42 (find_package)

-- Configuring incomplete, errors occurred!
```
I see that `zlib-1.2.11` is included in `rescal-snow/lib/`, but it doesn't seem to be properly linked by default, at least on my machine. The installation proceeded without that error after manually installing `zlib1g-dev`:
```
$ sudo apt-get install zlib1g-dev
```

**Comment by kellykochanski** [comment]
@r-barnes do you have time to take a look at this?

**Comment by kellykochanski** [comment]
This error also occurs on my new machine prior to installing zlib.

**Comment by kellykochanski** [comment]
@egreen77 I know it's been a while, but could you fill @r-barnes (who has made additional changes to the rescal build system) in on the work you did on the Rescal build system and the zlib dependency?

**Comment by r-barnes** [comment]
I don't think there's much light to be shed on this from that direction: I've replaced zlib with an upgraded version and replaced the build system with cmake, so there's not a lot of original structure left.

**Comment by r-barnes** [comment]
Since cmake has superior package management, the simplest solution here may be to drop both zlib and libpng from the codebase and request the user install these manually. cmake can enforce package versions that are known to work. @kellykochanski?

I'll keep checking in how to fix this using the existing setup, but haven't found solutions yet.

**Comment by kellykochanski** [comment]
@rgmyr We've resolved this issue (and the related issue about building with `cmake -Wno-dev -DCMAKE_BUILD_TYPE=Release`). 

Libpng and zlib are now explicit dependencies and are not packaged with the software.

**Comment by r-barnes** [comment]
Closing this for now.
