### ISSUE TITLE
JOSS Review (@rgmyr): Release build fails

### ISSUE THREAD

**Issue by rgmyr** [kellykochanski/rescal-snow#27]
`make` failed to build after configuring with `-DCMAKE_BUILD_TYPE=Release`. I also tried adding a `-Wno-error` flag to the `make` command, but that didn't seem to have any effect. 

I've attached the output: [Release_build_make_output.txt](https://github.com/kellykochanski/rescal-snow/files/3601982/Release_build_make_output.txt). It fails after building/linking `zlib` objects, so maybe this is related to my other issue.

I was able to build after running `cmake` with `-DCMAKE_BUILD_TYPE=Debug`, after which the example scripts seem to be working as expected.

**Comment by kellykochanski** [comment]
@r-barnes Do you have time to take a look at this one?

**Comment by r-barnes** [comment]
@rgmyr: What OS are you building on?

**Comment by rgmyr** [comment]
@r-barnes I'm on [Pop!_OS 19.04](https://distrowatch.com/table.php?distribution=popos), which is Ubuntu-based. My home machine is vanilla Ubuntu 16.04, so I can also check tonight and see if I get the same issue there.

**Comment by kellykochanski** [comment]
@r-barnes I reproduced this bug, and the associated zlib issue, on Ubuntu Budgie.

**Comment by kellykochanski** [comment]
@egreen77 I now get the following build error:

```bash
make[2]: *** No rule to make target '../lib/zlib-1.2.11/libz.a', needed by 'bin2png'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 94%] Building C object CMakeFiles/bin2png.dir/src/bin2png.c.o
make[2]: *** No rule to make target '../lib/zlib-1.2.11/libz.a', needed by 'csp2png'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 94%] Building C object CMakeFiles/csp2png.dir/src/csp2png.c.o
[ 95%] Building C object CMakeFiles/rescal.dir/src/drand48.c.o
[ 96%] Building C object CMakeFiles/rescal.dir/src/entry.c.o
make[2]: *** No rule to make target '../lib/zlib-1.2.11/libz.a', needed by 'rescal'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 96%] Building C object CMakeFiles/rescal.dir/src/rescal.c.o
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/bin2png.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:295: CMakeFiles/rescal.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:147: CMakeFiles/csp2png.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by r-barnes** [comment]
@rgmyr: Do you know your compiler version? Most compilers are getting progressively better at detecting warning conditions, so we'd prefer to resolve those whenever possible rather than using `-Wno-error`.

**Comment by rgmyr** [comment]
Just for reference, my `gcc --version` is `8.3.0`. Release build now works after installing `libpng-dev` and `zlib1g-dev`.
