### ISSUE TITLE
Need to run ./autogen.sh before compiling on kelly's laptop

### ISSUE THREAD

**Issue by kellykochanski** [kellykochanski/rescal-snow#3]
Initial ./configure make fails; ./autogen.sh modifies:

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   Makefile.in
	modified:   aclocal.m4
	modified:   autom4te.cache/output.0
	modified:   autom4te.cache/output.1
	modified:   autom4te.cache/requests
	modified:   autom4te.cache/traces.0
	modified:   autom4te.cache/traces.1
	modified:   configure
	modified:   lib/Makefile.in
	modified:   lib/libpng-1.6.34/Makefile.in
	modified:   lib/libpng-1.6.34/aclocal.m4
	modified:   lib/libpng-1.6.34/autom4te.cache/output.0
	modified:   lib/libpng-1.6.34/autom4te.cache/output.1
	modified:   lib/libpng-1.6.34/autom4te.cache/requests
	modified:   lib/libpng-1.6.34/autom4te.cache/traces.0
	modified:   lib/libpng-1.6.34/autom4te.cache/traces.1
	modified:   lib/libpng-1.6.34/configure
	modified:   src/Makefile.in

**Comment by r-barnes** [comment]
New `cmake` build system should fix this.
