### ISSUE TITLE
JOSS Review (@zbeekman): Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by zbeekman** [kellykochanski/rescal-snow#35]
The linked LAVA contributing guide is quite long. In addition, GitHub reminds users to check CONTRIBUTING.md, if it's present, when filing new issues or opening PRs.

It doesn't have to be long or complicated, but I think it would be useful to describe:

- The workflow, e.g., https://guides.github.com/introduction/flow/ vs https://datasift.github.io/gitflow/IntroducingGitFlow.html
- Expectations of contributors
- Acceptable contributions & issues
- Basic info (can just be links) on forking, commiting and opening a PR

**Comment by zbeekman** [comment]
See https://help.github.com/articles/setting-guidelines-for-repository-contributors/ for some ideas

**Comment by kellykochanski** [comment]
@zbeekman Added contributing.md: 
https://github.com/kellykochanski/rescal-snow/blob/kk/JOSS-fixes/CONTRIBUTING.md

**Comment by zbeekman** [comment]
@kellykochanski Awesome!

Two things:

1. If you are adding a code of conduct (contributor covenant, etc.) it should go in its own CODE_OF_CONDUCT.md file in the root of repository. This is common practice and GitHub will find it and understand that its there & enable bells and whistles associated with it. While I did not ask for a CODE_OF_CONDUCT.md, I do think it's always good to establish expectations for treating each other fairly & professionally so I appreciate that you added one!
2. It looks like you need a space in your H2 heading between `##` and the text. Older github flavored markdown (GFM) used to allow this without a space but the new rendering engine does not.

Looking good. Once you fix the formatting and separate the `CODE_OF_CONDUCT.md` (Or delete it if you really want to although I would discourage that...) I think this issue is resolved.

**Comment by kellykochanski** [comment]
@zbeekman Great! I've separated the files and fixed the typo. Marking this closed.

**Comment by zbeekman** [comment]
LGTM!
