### ISSUE TITLE
JOSS-Review (@zbeekman): Consider adding issue and PR templates

### ISSUE THREAD

**Issue by zbeekman** [kellykochanski/rescal-snow#36]
This is not mandatory for willing to accept the JOSS submission, however, at the Homebrew project, and OpenCoarrays we've found issue templates to be helpful in encouraging people to submit reproducible bug reports and making their contributions more useful.

https://github.com/kellykochanski/rescal-snow/community has some info.

See the contents of https://github.com/Homebrew/brew/tree/master/.github and https://github.com/Homebrew/brew/tree/master/.github/ISSUE_TEMPLATE for more info on templates.

**Comment by kellykochanski** [comment]
@zbeekman I think this is a good idea to help people with bug reports, but might leave this until after the JOSS review (or for the next time there's an influx of users/contributors).

**Comment by zbeekman** [comment]
Yup, feel free to close if you like.
