### ISSUE TITLE
JOSS-Review (@zbeekman): More prominent ack of original ReSCAL

### ISSUE THREAD

**Issue by zbeekman** [kellykochanski/rescal-snow#37]
I think you should add a more prominent acknowledgment of the original ReSCALE and its authors in the `README.md`. As it stands there is not much obvious indication of the history, heritage and relationship of Rescale-snow to ReSCALE. Furthermore, the changes relative to the original are not obvious/easy to find. I believe the GPL requires you to enumerate the changes made from the original software.

To address this I think you should add the following to the README.md:

- A more prominent description of the relationship with ReSCALE
  - Is this a fork of/from ReSCALE?
  - Which version (tag or commit SHA) of ReSCALE did you start from?
  - Are you including upstream changes from ReSCALE (if it is actively maintained) and merging these into Rescale-snow?
  - Have you considered contributing your changes back upstream?
    - A justification of the resulting decision
- A more prominent link to the Changelog/changes from the original ReSCALE

It looks like you have a change log under `docs/NEWS.md`. I would propose that you make this more legible by using bullets for sub-items rather than a one paragraph sentence per-sub item. I can submit a PR showing what I mean if you like.

---

__Optional:__

Many projects put a `CHANGELOG.md` in the root of the repository. (Or `NEWS.md`) This makes it more prominent. I personally prefer CHANGELOG.md but if the original ReSCALE uses `NEWS.md` or `NEWS` then you should probably follow that convention.

In addition, I think it would be good to move `AUTHORS.md` to the project root as well to make it more prominent.

Neither of these files are user or developer documentation in my opinion, and convention is typically locate them in the project root directly vs `./docs`.

**Comment by zbeekman** [comment]
I think I misspelled ReSCAL everywhere, but my meaning should be clear enough.

**Comment by kellykochanski** [comment]
Added statement to README:

> Rescal-snow branched off of ReSCAL (v1.6) in 2016, and continues to use the ReSCAL backend for the cellular automaton and lattice gas models. This history is described in [NEWS.md](NEWS.md) and the original code is available on branch `rescal-1.6`. Ongoing ReSCAL development is described at [http://www.ipgp.fr/~rozier/rescal/rescal.html](http://www.ipgp.fr/~rozier/rescal/rescal-fr.html) (the English version of this website is updated less regularly than the French). Our code is no longer easily compatible with ReSCAL, as we have removed features, unused code, and dependencies that were not related to wind-blown snow and reduced performance on high-performance computing systems. We are adopting a small fraction of new ReSCAL features on a case-by-case basis depending on their relevance to wind blown snow.

**Comment by kellykochanski** [comment]
(Links to NEWS currently broken; it'll work once NEWS is moved.)

**Comment by kellykochanski** [comment]
AUTHORS.md is also in the root directory.

**Comment by kellykochanski** [comment]
@zbeekman I believe the points raised in this issue are now addressed.

**Comment by zbeekman** [comment]
Looks good to me. I'll close this. I commented on the `NEWS.md` file: I think removing the extra space between successive bullets would improve legibility, but at this point that's just a nit; adjust the style however you see fit.
