### ISSUE TITLE
JOSS Review (@zbeekman): Parameter space setup script creates directories w/ executables that have bad permissions

### ISSUE THREAD

**Issue by zbeekman** [kellykochanski/rescal-snow#45]
The script `param_space_exploration_example.py` does not copy in `genesis` and `rescal` with the correct permissions. Following the advice:

>Running ./run.run in this test_parallel_runs/tauMin0_lambdaI0.001 directory would begin a rescal-snow run (you may wish to test this now).

leads to errors because the copied files do not have the executable bit set.

**Comment by zbeekman** [comment]
Also, the names of some files are wrong in the tutorial document, e.g., the tutorial lists the job submission files as

```
test_parallel_runs.msub
test_parallel_runs.sbatch
```

When in reality they are called

```
run_parallel_rescal.msub
run_parallel_rescal.sbatch
```

**Comment by kellykochanski** [comment]
The permissions should be addressed at the time you submit the parallel job; `scripts/submit.sh` runs `chmod u+rwx *` on the executables.

**Comment by kellykochanski** [comment]
This issue is also addressed in the tutorial under *troubleshooting for parallel runs* - this section had the copy-paste errors you found in your code review, but should now be clear. I've added an explicit note about `chmod u+x` alongside the directions to call `.run.run.`

**Comment by kellykochanski** [comment]
And the `run_parallel_rescal.msub` name is now corrected in the tutorial; good catch.

**Comment by zbeekman** [comment]
> The permissions should be addressed at the time you submit the parallel job; `scripts/submit.sh` runs `chmod u+rwx *` on the executables.

Yes, I just noticed that after trying to run stuff by hand, as recommended in the tutorial.

> This issue is also addressed in the tutorial under _troubleshooting for parallel runs_ - this section had the copy-paste errors you found in your code review, but should now be clear. I've added an explicit note about `chmod u+x` alongside the directions to call `.run.run`.

I still think it would be more robust/wiser to set the permissions correctly in the python script instead of indiscriminately giving everything--data files and executables--the executable bit. But, addressing it in the troubleshooting is probably sufficient, as long as you don't mind annoying your users 😆
