### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by r-barnes** [kellykochanski/rescal-snow#6]
`docs/how_to_install.md` is a missing file.

I think the installation instructions should be:
```
./autogen.sh
./configure
make
```

**Comment by kellykochanski** [comment]
docs/how_to_install.md is in branch release-rescal-snow-1.1

**Comment by kellykochanski** [comment]
./autogen.sh runs aclocal and autoreconf.

In most cases, the output from autoreconf should be portable across platforms. Running ./autogen.sh on these platforms adds a new and largely avoidable dependency on autoconf.

**Comment by kellykochanski** [comment]
Resolved in pull request #13
